# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca41e0ce4c0e8d30e8efb78ab8160c92ea688ed979fa2c413390904d1c6349f5a3e1f00fe4dfb6b44ac524252362665e026dd7ebd079ba458eb73c4a7ef48931

test:
  secret_key_base: 4f19ea7793967a7f50c16dd0f1556e97d90bf0a72c74a29e11ebfd43f5b0adba60d755089a48726a27d92fdd8a9f7d1eed2c2932d6eaaa5e522c4889ebff30d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
